name: Continuous Deployment from main branch
on:
  push:
    branches:
      - main
    paths:
      - ./swipe-vue/**
        
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    defaults: 
      run:
        working-directory: ./swipe-vue

    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Run build
        run: npm run build

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: releases the latest website
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
